import Head from "next/head"
// import MainContent from "../components/MainContent"
import { request } from "../lib/datocms"
import { Image } from "react-datocms"

export default function Home({ content: { homePage } }) {
  const {
    heading: {
      value: {
        document: { children },
      },
    },
  } = homePage

  const headingStart = children[0].children[0].value
  const headingSpan = children[1].children[0].value
  const headingEnd = children[2].children[0].value

  return (
    <>
      <Head>
        <title>
          Swiftweb Digital | Professional website development served swiftly
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article className="w-full h-screen overflow-hidden relative">
        <section className="overlay">
          <div className="container">
            <div className="banner-content">
              <h1 className="banner-title">
                {headingStart}
                <br />
                <span className="highlight">{headingSpan}</span> {headingEnd}
              </h1>
              <h2 className="strapline">{homePage.strapline}</h2>
            </div>
          </div>
        </section>
        <figure className="relative h-full w-full">
          <Image
            data={homePage.bannerImage.responsiveImage}
            alt={homePage.bannerImage.alt}
          />
        </figure>
      </article>
    </>
  )
}

const HOMEPAGE_QUERY = `query Homepage {
  homePage {
    id
    bannerImage {
      alt
      url
      responsiveImage {
        alt
        aspectRatio
        bgColor
        height
        sizes
        src
        srcSet
        width
      }
    }
    strapline
    heading {
      value
    }
  }
}`

export async function getServerSideProps() {
  const content = await request({
    query: HOMEPAGE_QUERY,
  })
  return {
    props: { content },
  }
}
