import Head from "next/head"
import MainContent from "../components/MainContent"
import { request } from "../lib/datocms"
import Image from "next/image"

export default function Home({ content: { homePage } }) {
  // console.log(homePage)
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article className="w-full h-screen overflow-hidden relative">
        <section className="overlay">
          <div className="container">
            <div className="banner-content">
              <h1 className="banner-title">{homePage.heading}</h1>
              <h2 className="strapline">{homePage.strapline}</h2>
            </div>
          </div>
        </section>
        <figure className="relative h-full w-full">
          <Image
            src={homePage.bannerImage.url}
            alt={homePage.bannerImage.alt}
            layout="fill"
            objectFit="cover"
          />
        </figure>
      </article>
    </>
  )
}

const HOMEPAGE_QUERY = `query Homepage {
  homePage {
    id
    heading
    bannerImage {
      alt
      url
    }
    strapline
  }
}`
export async function getStaticProps() {
  const content = await request({
    query: HOMEPAGE_QUERY,
  })
  return {
    props: { content },
  }
}
