import Head from "next/head"
// import MainContent from "../components/MainContent"
import { request } from "../lib/datocms"
import { Image } from "react-datocms"
import ReactMarkdown from "react-markdown"

export default function Home({ content: { homePage } }) {
  const {
    heading: {
      value: {
        document: { children },
      },
    },
  } = homePage

  const headingStart = children[0].children[0].value
  const headingSpan = children[1].children[0].value
  const headingEnd = children[2].children[0].value

  return (
    <>
      <Head>
        <title>
          Swiftweb Digital | Professional website development served swiftly
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article className="w-full h-full max-h-screen min-h-[500px] overflow-hidden relative">
        <section className="overlay">
          <div className="container">
            <div className="banner-content">
              <h1 className="banner-title">
                {headingStart}
                <br />
                <span className="highlight">{headingSpan}</span> {headingEnd}
              </h1>
              <h2 className="strapline">{homePage.strapline}</h2>
            </div>
          </div>
        </section>
        <figure className="h-screen bg-grey-200">
          <Image
            src={homePage.bannerImage.url}
            data={homePage.bannerImage.responsiveImage}
            alt={homePage.bannerImage.alt}
            objectFit="cover"
            layout="fill"
            lazyload="true"
          />
        </figure>
      </article>
      <article className="bg-white py-16">
        <div className="container markdown">
          <h2 className="title">{homePage.introHeading}</h2>
          <ReactMarkdown>{homePage.introParagraph}</ReactMarkdown>
        </div>
      </article>
    </>
  )
}

const HOMEPAGE_QUERY = `query Homepage {
  homePage {
    id
    bannerImage {
      alt
      url(imgixParams: {fit: fill})
      responsiveImage(imgixParams: {fit: fill}) {
        height
        src
        srcSet
        width
      }
    }
    strapline
    heading {
      value
    }
    introHeading
    introParagraph
  }
}`

export async function getServerSideProps() {
  const content = await request({
    query: HOMEPAGE_QUERY,
  })
  return {
    props: { content },
  }
}
